name: MusicalRegions
author: JCThePants
main: com.jcwhatever.musical.MusicalRegions
version: 0.0-beta
depend: [NucleusFramework]
commands:
    musicalregions:
        aliases: [music, musical]
        description: Base command for Musical Regions
        usage: |
            ERROR!