name: MusicalRegions
author: JC The Pants
main: com.jcwhatever.bukkit.musical.MusicalRegions
version: 0.2
depend: [jcGenerics]
commands:
    musical:
        description: Base command for Musical Regions
        usage: |
            ERROR!
    music:
        description: Base command for Musical Regions
        usage: |
            ERROR!
    musicalregions:
        description: Base command for Musical Regions
        usage: |
            ERROR!