name: MusicalRegions
author: JCThePants
main: com.jcwhatever.bukkit.musical.MusicalRegions
version: 0.0-beta
depend: [NucleusFramework]
commands:
    musical:
        aliases: [music, musicalregions]
        description: Base command for Musical Regions
        usage: |
            ERROR!